Fixed corner-case with complex words with their part in vocabulary
Melevir/rozental_as_a_service pull request #5
Opened 2019-07-31 19:58 UTC by LerikP

Bump self-dependency version
Reorder vocabulary

2019-08-01 22:18 UTC, Melevir commented on rozental_as_a_service/typos_backends.py
> +    correct_words = {w for w in words if any(part in vocabulary for part in w.split('-'))}
Кажется, что это не должно так работать. "аппиум" и "аппиум-сервер" – это два разных слова и если одна часть написана верно, это не значит, что опечатки нет в другой. Например, этот код сочтёт, что "аппиум-срвр" – правильное слово, а это не так.

2019-08-01 22:18 UTC, Melevir requested changes
Бамп дев-версии и новый тест – это очень круто, спасибо. 
А вот с новой логикой есть проблемы.

2019-08-04 06:05 UTC, LerikP commented on rozental_as_a_service/typos_backends.py
> +    correct_words = {w for w in words if any(part in vocabulary for part in w.split('-'))}
Выпилил это исправление

2019-08-04 06:06 UTC, LerikP commented
На винде развалилось чтение словаря :(, пришлось принудительно кодировку ему прикрутить

2019-08-04 06:33 UTC, merged

2019-08-04 06:33 UTC, Melevir commented
Спасибо :)